trainer:
  target: trainers.ldm_trainer.LDMTrainer
  batch_size: 512
  num_workers: 2
  learning_rate: 1e-5
  num_iters: 5000
  val_every: 100
  num_val_iters: 5

  use_wandb: true
  wandb_entity: 
  wandb_project: 
dit:
  in_channels: 3
  num_channels: 384
  depth: 12
  num_heads: 6
  patch_size:
    - 1
    - 2
    - 2
  use_rope: true
  rope_ndim: 2
  mlp_ratio: 4.0
  t_dim: 256
  num_classes: 10
